name: Build Nuxt 3 Application

on:
  push:
    branches:
      - main # или другая ветка по Вашему выбору

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload dist folder
        uses: actions/upload-artifact@v2
        with:
          name: nuxt-dist
          path: dist/
